### PR TITLE
add bytes random generator

### PR DESCRIPTION
**Pull request by HamzaBenyazid**

### CODE REVIEW

**Review by oubaydos — CHANGES_REQUESTED** [review]
replace Math.random() by random.nextInt+ fix the javadoc for the getBytes method

**Review by mosle77 — DISMISSED** [review]

**Comment by HamzaBenyazid** [comment]
> replace Math.random() by random.nextInt+ fix the javadoc for the getBytes method

I changed Math.random(), but I think javadoc is good. byte[].class.getName() returns [B and Byte[].class.getName() returns [Ljava.lang.Byte

**Review by oubaydos — CHANGES_REQUESTED** [review]
do you think its a good idea to push .idea folder, as not everyone uses intellij ! ( i noticed that you did not push the whole folder )

**Comment by oubaydos** [comment]
@HamzaBenyazid YO

**Comment by HamzaBenyazid** [comment]
> do you think its a good idea to push .idea folder, as not everyone uses intellij ! ( i noticed that you did not push the whole folder )

Done

**Review by oubaydos — APPROVED** [review]

**Pull request merged**
