### PR TITLE
configure logger

### PR DESCRIPTION
**Pull request by HamzaBenyazid**

### CODE REVIEW

**Review by oubaydos — APPROVED** [review]
why did u use logback instead of slf4j ?

**Comment by HamzaBenyazid** [comment]
> why did u use logback instead of slf4j ?

I used slf4j with logback. slf4j is not a logging framework, it's an abstraction layer for Java logging frameworks. It has its own framework slf4j-simple , but it doesn't give you a way to customize the logger, it only gives the red logs, that's why I used logback.
check this [tutorial](https://sematext.com/blog/slf4j-tutorial/#toc-using-slf4j-with-logging-framework-at-the-deploy-time-3)

**Comment by HamzaBenyazid** [comment]
> > why did u use logback instead of slf4j ?
> 
> I used slf4j with logback . slf4j is not a logging framework, it's an abstraction layer for Java logging frameworks. It has its own framework slf4j-simple , but it doesn't give you a way to customize the logger, it only gives the red logs, that's why I used logback. check this [https://sematext.com/blog/slf4j-tutorial/#toc-using-slf4j-with-logging-framework-at-the-deploy-time-3](url)

**Comment by oubaydos** [comment]
actually, it has other implementations (check https://www.slf4j.org/manual.html#swapping)

**Comment by HamzaBenyazid** [comment]
> actually, it has other implementations (check https://www.slf4j.org/manual.html#swapping)

Those are not implementations. Those are bindings with logging frameworks . And I choosed slf4j-logback because I found that logback is better than log4j (read [This](https://www.educba.com/log4j-vs-logback/) ) and those are the most popular frameworks.

**Pull request merged**
