### PR TITLE
Implement getRandomMap and refactor getRandomObject method

### PR DESCRIPTION
**Pull request by HamzaBenyazid**
getRandomMap returns by default a HashMap
I will add later methods for generating other types of maps ( TreeMap ....)

### CODE REVIEW

**Review by oubaydos — COMMENTED** [review]
you can return Character.toLowerCase(fieldName.charAt(0))+fieldName.substring(1); without setting it first to fieldName

**Review by oubaydos — CHANGES_REQUESTED** [review]
if we cant get rid of the warning in getRandomObject you may use 
```
@SuppressWarnings({"unchecked","rawtypes"})
    public Object getRandomObject(Type type)
```

**Review by oubaydos — CHANGES_REQUESTED** [review]
```getRandomMap``` should be private

**Review by oubaydos — COMMENTED** [review]
nice work @HamzaBenyazid

**Comment by HamzaBenyazid** [comment]
> if we cant get rid of the warning in getRandomObject you may use
> 
> ```
> @SuppressWarnings({"unchecked","rawtypes"})
>     public Object getRandomObject(Type type)
> ```

I think we should let the warnings, so that we get notified and try to find better solution. Unless if you think that this is the final solution.

**Review by oubaydos — APPROVED** [review]

**Pull request merged**
