### PR TITLE
Mosleh

### PR DESCRIPTION
**Pull request by mosle77**
Added methods to generate random short, long, float numbers and boolean

### CODE REVIEW

**Comment by oubaydos** [comment]
Please remove the .idea folder as it contains your IDE configuration and should not be pushed

**Comment by mosle77** [comment]
done


> Please remove the .idea folder as it contains your IDE configuration and should not be pushed

done

**Review by oubaydos — CHANGES_REQUESTED** [review]
good, please add javadocs before we can merge the pr

**Review by oubaydos — APPROVED** [review]
👍

**Pull request merged**
